### ISSUE TITLE
Re-enable security checks 

### ISSUE THREAD

**Issue by RudyBricks** [baloise/ws-angular_slides#37]
Dear code owners and users of ws-angular_slides,

we noticed that you had difficulties in patching security issues reported by github security check.
In order to avoid further notification spamming, we had to turn of the security checks for this repository.

If you, however, have the desire to keep this software free of issues (which I encourage you to do), please go ahead and re-enable security checks by yourself in "GitHub Settings" -> "Options" -> "Data Services" -> "Security alerts".

Cheers & happy coding,
Rudi

**Comment by joachimprinzbach** [comment]
Closing this, as it is a presentation and there is imo no need to fix those issues.
